# feeder
feeder: feeders.feeder_squats.Feeder
train_feeder_args:
  data_path: joint
  label_path: train
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 100
  normalization: False
  repeat: 1

test_feeder_args:
  data_path: joint
  label_path: val
  debug: False


# model
model: model.Hyperformer.Model
model_args:
  num_class: 5
  num_point: 19
  num_person: 1
  graph: graph.squats.Graph
  graph_args:
    labeling_mode: 'spatial'
  joint_label: [0, 0, 1, 1, 1, 0, 2, 2, 2, 3, 3, 4, 4, 4, 3, 3, 4, 4, 4]

#optim
# weight_decay: 0
weight_decay: 0.0003
base_lr: 0.02
lr_decay_rate: 0.1
#step: [120, 130]
step: [110, 120]

# training
device: 0
batch_size: 16
test_batch_size: 64
num_epoch: 300
nesterov: True
warm_up_epoch: 5
